In [1]:
!pip install pandas==1.0.0

In [3]:
import pandas as pd
import numpy as np

In [4]:
arr = np.random.randint(0, 10, size=(5, 3))
print(arr)

[[8 9 1]
 [2 8 7]
 [7 7 6]
 [3 3 5]
 [8 2 1]]


In [5]:
# Создание фрейма - просто вызвать конструктор
df = pd.DataFrame(data=arr)
# Фреймы удобнее отображать с помощью встроенных средств Jupyter
df

0  1  2
0  8  9  1
1  2  8  7
2  7  7  6
3  3  3  5
4  8  2  1

ЗАДАНИЕ 1: Создайте фрейм с именами колонок 'col_1', 'col_2', 'col_3' и индексами по алфавиту ('A', 'B', 'C', ... или 'A', 'Б', 'В', ...).

In [11]:
arr = np.random.randint(0, 10, size=(5, 3))
index = np.array(['A', 'B', 'C', 'D', 'E'])
columns = np.array(['col_1', 'col_2', 'col_3'])
df = pd.DataFrame(data=arr, columns = columns, index = index)
df

col_1  col_2  col_3
A      6      8      7
B      2      5      7
C      6      6      4
D      4      1      6
E      8      8      5

In [12]:
# Создается словарь, в котором ключи будут названиями колонок,
#   а значения - данные по этим колонкам
data = {
    'test_1_mark': [4.6, 3.8, 5.0, 4.5],
    'test_2_mark': [5.0, 3.9, 4.7, 4.5]
}

pd.DataFrame(data)

test_1_mark  test_2_mark
0          4.6          5.0
1          3.8          3.9
2          5.0          4.7
3          4.5          4.5

In [13]:
data = [
    {
        'test_1_mark': 4.6,
        'test_2_mark': 5.0
    },
    {
        'test_1_mark': 3.8,
        'test_2_mark': 3.9
    },
    {
        'test_1_mark': 5.0
    },
]

pd.DataFrame(data)

test_1_mark  test_2_mark
0          4.6          5.0
1          3.8          3.9
2          5.0          NaN

In [17]:
df = pd.DataFrame({'A': 1.,
                   'B': pd.Timestamp('20130102'),
                   'C': np.array([2.] * 4, dtype='float32'),
                   'D': np.array([3] * 4, dtype='int32'),
                   'E': pd.Categorical(["test", "train", "test", "train"]),
                   'F': 'foo'})
df

A          B    C  D      E    F
0  1.0 2013-01-02  2.0  3   test  foo
1  1.0 2013-01-02  2.0  3  train  foo
2  1.0 2013-01-02  2.0  3   test  foo
3  1.0 2013-01-02  2.0  3  train  foo

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   A       4 non-null      float64       
 1   B       4 non-null      datetime64[ns]
 2   C       4 non-null      float32       
 3   D       4 non-null      int32         
 4   E       4 non-null      category      
 5   F       4 non-null      object        
dtypes: category(1), datetime64[ns](1), float32(1), float64(1), int32(1), object(1)
memory usage: 356.0+ bytes


In [18]:
df = pd.DataFrame(
    data=np.random.randint(-10, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)

# Функция получения первых записей фрейма
# Аргументом задается количество выводимых данных
#   Если не задано - 5 по-умолчанию
df.head(4)

x1  x2  x3
0  -7  -6  -2
1  -6  -7   7
2   3  -5  -2
3  -4  -8 -10

In [19]:
# Функция получения последних записей фрейма
# Аргументом задается количество выводимых данных
#   Если не задано - 5 по-умолчанию
df.tail(4)

x1  x2  x3
11  -9  -9  -2
12   2  -7   3
13  -5  -4   5
14   3   9  -2

In [20]:
# Функция отображения основной информации о фрейме:
#   Количество записей
#   Типы колонок
#   Количество ненулевых значений
#   Тип индекса
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      15 non-null     int32
 1   x2      15 non-null     int32
 2   x3      15 non-null     int32
dtypes: int32(3)
memory usage: 308.0 bytes


In [21]:
# Функция отображения статистики по численным колонкам
df.describe()

x1         x2         x3
count  15.000000  15.000000  15.000000
mean   -1.933333  -3.666667  -0.466667
std     5.338093   6.007931   5.208052
min    -9.000000 -10.000000 -10.000000
25%    -6.500000  -7.500000  -2.000000
50%    -4.000000  -6.000000  -1.000000
75%     3.000000  -2.500000   4.000000
max     6.000000   9.000000   7.000000

In [22]:
# Атрибут получения индексов фрейма
df.index

RangeIndex(start=0, stop=15, step=1)

In [23]:
# Или чтобы представить в виде списка
list(df.index)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [24]:
# Или чтобы представить в виде списка
list(df.index)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [25]:
# Преобразование к двумерному массиву numpy
df.to_numpy()

array([[ -7,  -6,  -2],
       [ -6,  -7,   7],
       [  3,  -5,  -2],
       [ -4,  -8, -10],
       [  0,   4,  -1],
       [  6,   8,  -5],
       [  4,  -3,  -1],
       [ -8,  -7,   4],
       [  5,  -8,   4],
       [ -6, -10,   5],
       [ -7,  -2, -10],
       [ -9,  -9,  -2],
       [  2,  -7,   3],
       [ -5,  -4,   5],
       [  3,   9,  -2]])

In [26]:
# Получение транспонированного представления
# Колонки -> ряды, ряды -> колонки
df.T

0  1  2   3  4  5  6  7  8   9  10  11  12  13  14
x1 -7 -6  3  -4  0  6  4 -8  5  -6  -7  -9   2  -5   3
x2 -6 -7 -5  -8  4  8 -3 -7 -8 -10  -2  -9  -7  -4   9
x3 -2  7 -2 -10 -1 -5 -1  4  4   5 -10  -2   3   5  -2

In [27]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    columns=['x1', 'x2', 'x3']
)

df

x1  x2  x3
0   4   1   2
1   5   9   9
2   4   7   8
3   9   2   6
4   1   0   2

In [28]:
print(df['x1'])
print(type(df['x1']))

0    4
1    5
2    4
3    9
4    1
Name: x1, dtype: int32
<class 'pandas.core.series.Series'>


In [29]:
data = {
    'feature1': np.arange(15),
    'feature2': np.linspace(0, 10, 15),
    'feature3': 'string',
}
df = pd.DataFrame(data, index=list('ABCDEFGHIJKLMNO'))
df.head()

feature1  feature2 feature3
A         0  0.000000   string
B         1  0.714286   string
C         2  1.428571   string
D         3  2.142857   string
E         4  2.857143   string

In [30]:
df.iloc[2]

feature1          2
feature2    1.42857
feature3     string
Name: C, dtype: object

In [31]:
df.loc['C']

feature1          2
feature2    1.42857
feature3     string
Name: C, dtype: object

In [32]:
df.iloc[2, 1]

1.4285714285714286

In [33]:
df.loc['C', 'feature2']

1.4285714285714286

ЗАДАНИЕ 2: Выведите часть фрейма со второго ряда по девятый (индексы с 'C' по 'I') и только feature1 и feature3:

In [34]:
data = {
    'feature1': np.arange(15),
    'feature2': np.linspace(0, 10, 15),
    'feature3': 'string',
}
df = pd.DataFrame(data, index=list('ABCDEFGHIJKLMNO'))
df.head()

feature1  feature2 feature3
A         0  0.000000   string
B         1  0.714286   string
C         2  1.428571   string
D         3  2.142857   string
E         4  2.857143   string

In [46]:
df.loc['C': 'I', ['feature1', 'feature3']]

feature1 feature3
C         2   string
D         3   string
E         4   string
F         5   string
G         6   string
H         7   string
I         8   string

In [48]:
df.iloc[2: 9, [0, 2]]

feature1 feature3
C         2   string
D         3   string
E         4   string
F         5   string
G         6   string
H         7   string
I         8   string

In [49]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   5   3   0
1   6   3   9
2   7   0   0

In [50]:
df['x1'] > 5

0     False
1      True
2      True
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10     True
11    False
12    False
13    False
14    False
Name: x1, dtype: bool

In [52]:
mask = df['x1'] > 5
df[mask]

# Или df[df['x1'] > 5]

x1  x2  x3
1    6   3   9
2    7   0   0
7    8   4   4
10   8   9   4

In [53]:
df[~(df['x1'] > 5)]

x1  x2  x3
0    5   3   0
3    0   7   6
4    0   0   5
5    1   7   5
6    3   1   3
8    5   0   0
9    4   8   5
11   5   8   7
12   3   3   5
13   5   9   4
14   4   1   7

ЗАДАНИЕ 3: Выберите записи во фрейме, которые по признаку x1 имеют значение больше 3, а по признаку x3 - меньше 8.

In [58]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)
mask1 = df['x1'] > 3
mask2 = df['x3'] < 8
df[mask1 & mask2]

x1  x2  x3
1    8   1   6
3    4   6   4
4    7   5   7
7    7   9   6
10   4   7   0
12   7   6   5
13   7   3   4

TODO - отфильтровать фрейм по значениям признаков:

In [63]:
mask1 & mask2

0     False
1      True
2     False
3      True
4      True
5     False
6     False
7      True
8     False
9     False
10     True
11    False
12     True
13     True
14    False
dtype: bool

Oтобразите только колонки x1 и x2 с учетом условий (используйте .loc[])

In [64]:
df[mask1 & mask2].loc[:, ('x1', 'x2')]

x1  x2
1    8   1
3    4   6
4    7   5
7    7   9
10   4   7
12   7   6
13   7   3

ЗАДАНИЕ 4: С помощью метода DataFrame.query() получите записи, которые соответсвуют условию сравнения колонок  x1>x3 :

In [65]:
df = pd.DataFrame(
    [[1, 2, 6], [5, 1, 1], [8, 4, 6], [4, 1, 1], [9, 9, 0], [-1, 2, 1], [5, 5, 5]],
    columns = ['x1', 'x2', 'x3']
)
df
df.query('x1 > x3')

x1  x2  x3
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0

Сделать аналогичное действие, но уже с помощью условной индексации

In [66]:
mask1 = df['x1'] > df['x3']
df[mask1]

x1  x2  x3
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0

In [67]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   8   3   5
1   9   3   7
2   2   8   1

In [68]:
# Создать новую колонку можно по аналогии с новым ключем в словаре
# Сложение нескольких Series и запись в новую колонку
df['x1+x2'] = df['x1'] + df['x2']
df.head(3)

x1  x2  x3  x1+x2
0   8   3   5     11
1   9   3   7     12
2   2   8   1     10

In [69]:
# Поэлементное умножение
df['x1*x3'] = df['x1'] * df['x3']
df.head(3)

x1  x2  x3  x1+x2  x1*x3
0   8   3   5     11     40
1   9   3   7     12     63
2   2   8   1     10      2

In [70]:
# Взятие среднего по колонке (метод Series.mean())
df['x1'].mean()

5.133333333333334

In [71]:
# Использование функций numpy для работы с колонками
df['x2_exp'] = np.exp(df['x2'])
df.head(3)

x1  x2  x3  x1+x2  x1*x3       x2_exp
0   8   3   5     11     40    20.085537
1   9   3   7     12     63    20.085537
2   2   8   1     10      2  2980.957987

In [72]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(3, 3)), 
    columns=['x1', 'x2', 'x3']
)
df

x1  x2  x3
0   4   8   7
1   6   8   3
2   6   4   6

In [73]:
# Обязательно требование к функции - один аргумент
# Эта функция будет передана в apply() и pandas
#   будет вызывать ее и передавать в нее 
#   по одному элементу из ряда
# Возвращать функция должна результат операции над элементом
def my_func(x):
    print(type(x))
    print(x)
    return x*2

df['result'] = df['x1'].apply(my_func)
df

<class 'int'>
4
<class 'int'>
6
<class 'int'>
6


x1  x2  x3  result
0   4   8   7       8
1   6   8   3      12
2   6   4   6      12

In [74]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   5   0   5
1   5   9   0
2   9   9   6

In [75]:
# Методу передается в аргумент columns словарь, 
#   в котором ключи - имена колонок,
#   значения - новые имена для переименования
df.rename(
    columns={
        'x1': 'new_name_for_x1',
        'x3': 'that_not_x3' 
    },
    inplace=True
)
df.head(3)

new_name_for_x1  x2  that_not_x3
0                5   0            5
1                5   9            0
2                9   9            6

ЗАДАНИЕ 5: Переименуйте индексы и колонки во фрейме

In [78]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    index=['A', 'B', 'C', 'D', 'E'], 
    columns=['x1', 'x2', 'x3']
)
df
df.rename(
    columns={
        'x1': 'new1',
        'x3': 'new3' 
    },
    index={
        'A':'indA',
        'C':'indC'
    },
    inplace=True
)
df

new1  x2  new3
indA     4   8     9
B        9   9     5
indC     1   5     8
D        1   6     2
E        2   4     5

In [79]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   0   7   3
1   4   5   7
2   5   0   9

In [80]:
df.drop(columns=['x2'], inplace=True)
df.head(3)

x1  x3
0   0   3
1   4   7
2   5   9

In [81]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.iloc[0, :2] = np.nan
df.iloc[2, 1:] = np.nan

df

x1   x2   x3
0  NaN  NaN  1.0
1  1.0  1.0  5.0
2  3.0  NaN  NaN
3  3.0  1.0  4.0
4  6.0  4.0  8.0

In [82]:
df.isna()

x1     x2     x3
0   True   True  False
1  False  False  False
2  False   True   True
3  False  False  False
4  False  False  False

In [83]:
df.isna().sum()

x1    1
x2    2
x3    1
dtype: int64

In [85]:
df['x2'].fillna(3, inplace=True)
df

x1   x2   x3
0  NaN  3.0  1.0
1  1.0  1.0  5.0
2  3.0  3.0  NaN
3  3.0  1.0  4.0
4  6.0  4.0  8.0

In [86]:
df = pd.DataFrame({
    'col1': ['high', 'high', 'low', 'med', 'low', 'low', 'med', 'low', 'low', 'high'],
    'col2': [0, 1, 1, 2, 3, 1, 1, 2, 2, 2]
})
df

col1  col2
0  high     0
1  high     1
2   low     1
3   med     2
4   low     3
5   low     1
6   med     1
7   low     2
8   low     2
9  high     2

In [87]:
# Метод DataFrame.nunique() позволяет вывести 
#   количество уникальных значений в каждой колонке
# Результат - Series с индексами - названиями колонок
df.nunique()

col1    3
col2    4
dtype: int64

In [88]:
# Метод Series.value_counts() показывает уникальные значения в ряду
#   и указывает их количество
df['col1'].value_counts()

low     5
high    3
med     2
Name: col1, dtype: int64

In [89]:
# Результат - Series с индексами - уникальными значениями
df['col2'].value_counts()

2    4
1    4
3    1
0    1
Name: col2, dtype: int64

In [90]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6])),
                  index=['mouse', 'rabbit'],
                  columns=['col_one', 'col_two', 'col_three'])
df

col_one  col_two  col_three
mouse         1        2          3
rabbit        4        5          6

In [91]:
# Отфильтровать по именам колонок
# Аналогично df[['col_one', 'col_three']]
df.filter(items=['col_one', 'col_three'], axis='columns')

col_one  col_three
mouse         1          3
rabbit        4          6

In [92]:
# Отфильтровать по регулярному выражению
# Оставить только те колонки, которые оканчиваются на букву "o"
df.filter(regex='o$', axis='columns')

col_two
mouse         2
rabbit        5

ЗАДАНИЕ 6: Отфильруйте записи по строке, содержащейся в имени индекса (аргумент like):

In [95]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9])),
                  index=['dog in house', 'cat in house', 'pig in farm'],
                  columns=['x1', 'x2', 'x3'])
df
df.filter(like='house', axis='index')

x1  x2  x3
dog in house   1   2   3
cat in house   4   5   6

In [96]:
df = pd.DataFrame({
    'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col2': [2, 1, 9, 8, 7, 4],
    'col3': [0, 1, 9, 4, 2, 3],
    'col4': ['a', 'B', 'c', 'D', 'e', 'F']
}, index=['A', 'B', 'C', 'D', 'E', 'F'])
df

col1  col2  col3 col4
A    A     2     0    a
B    A     1     1    B
C    B     9     9    c
D  NaN     8     4    D
E    D     7     2    e
F    C     4     3    F

In [97]:
# Отсортируем записи колонки col2
# Именно поэтому в axis ставится rows, так как
#   операция производится в колонке по каждому ряду
df.sort_values(by='col2', axis='rows')

col1  col2  col3 col4
B    A     1     1    B
A    A     2     0    a
F    C     4     3    F
E    D     7     2    e
D  NaN     8     4    D
C    B     9     9    c

In [103]:
df = pd.DataFrame(
    np.random.randint(0, 20, size=(5, 5)), 
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)
df
df.sort_values(by=3, axis='columns', ascending= False)

col4  col1  col5  col2  col3
0     6    16     9    16     2
1     1    13     3     8     7
2    10     3    13    12    11
3    18    17    14     8     0
4    18     1    15     4    19

In [104]:
df = pd.DataFrame({
    'temp': [59, 22, -10, 38, 20, 40, 38, 47, 20, 15, 13, 44, 57, 32, 38]
})
df.head()

temp
0    59
1    22
2   -10
3    38
4    20

In [ ]:
# Можно задать свои границы диапазона и названия категорий
# Если планируется три категории, то границ должно быть на одну больше - 
#   так задаются диапазоны для категорий
df['temp_cat'] = pd.cut(
    x=df['temp'],
    bins=[-10, 10, 25, 60],
    labels=['low', 'medium', 'high'],
    # Флаг, чтобы самое левое значение границы входило в первый диапазон
    include_lowest=True
)
df.head()

In [106]:
# Результат разделения имеет категориальный тип
df['temp_cat'].dtype

CategoricalDtype(categories=['low', 'medium', 'high'], ordered=True)

In [107]:
# Можно не задавать имена категориям, тогда он сам их назовет
result_after_cut = pd.cut(
    x=df['temp'],
    bins=[-10, 10, 25, 60],
    include_lowest=True
)
# Взглянем на имена
result_after_cut.unique()

[(25.0, 60.0], (10.0, 25.0], (-10.001, 10.0]]
Categories (3, interval[float64]): [(-10.001, 10.0] < (10.0, 25.0] < (25.0, 60.0]]

In [108]:
# Можно не задавать границы, лишь количество категорий - 
#   разделение будет на категории с одинаковой шириной диапазонов
result_after_cut = pd.cut(
    x=df['temp'],
    bins=3
)
result_after_cut.unique()

[(36.0, 59.0], (13.0, 36.0], (-10.069, 13.0]]
Categories (3, interval[float64]): [(-10.069, 13.0] < (13.0, 36.0] < (36.0, 59.0]]

ЗАДАНИЕ 7: Разделите показатель качества в диапазоне  [0,100]  на три группы: плохое  [0−20] , среднее  (20−45] , хорошее  (45−85] , отличное  (85−100] . Выясните, что происходит со значениями, которые не попадают в диапазоны категорий:

In [110]:
df = pd.DataFrame({
    'quality': [ 7, 67, 21, 38,  2, -2, 79, 22,  5, 31, 77, 72, 23, 64, 99]
})
df.head()
df['quality_cat'] = pd.cut(
    x = df['quality'],
    bins = [0, 20, 45, 85, 100],
    labels=['bad', 'medium', 'good', 'excellent'],
    include_lowest=True
)
df

quality quality_cat
0         7         bad
1        67        good
2        21      medium
3        38      medium
4         2         bad
5        -2         NaN
6        79        good
7        22      medium
8         5         bad
9        31      medium
10       77        good
11       72        good
12       23      medium
13       64        good
14       99   excellent

Не имеют категории те записи, которые не вошли в заданный диапазон качества. А конкретно отрицательное значение -2. Если бы было значение больше 100 оно бы тоже не имело категории. 

In [111]:
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [np.nan, np.nan, np.nan]],
                  columns=['A', 'B', 'C'])
df

A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [112]:
# Получим значения минимумов и средних по всем колонкам
# Принцип аналогичен операциям в numpy - 
#   для агрегации по колонка операция должна пройти по рядам,
#   соответсвенно, axis='rows'
df.aggregate(['min', 'mean'], axis='rows')

A    B    C
min   1.0  2.0  3.0
mean  4.0  5.0  6.0

In [113]:
# Зададим правила агрегации для каждой колонки
# Операции можно задавать строками или функциями numpy
df.aggregate({
    'A': ['sum', 'min'],
    'B': ['max', 'min'],
    'C': [np.sum, np.mean],
})

A    B     C
max    NaN  8.0   NaN
mean   NaN  NaN   6.0
min    1.0  2.0   NaN
sum   12.0  NaN  18.0

In [117]:
df = pd.DataFrame(
    ([1, 2, 3], [4, 5, 6], [7, 8, 9]), 
    columns=['x1', 'x2', 'x3'])
df
df.aggregate(['mean'], axis='columns')

mean
0   2.0
1   5.0
2   8.0

In [118]:
data = [
    [1, 4.7, 60],
    [3, 4.5, 45],
    [4, 4.8, 40],
    [1, 4.9, 58],
    [2, 4.1, 50],
    [2, 4.2, 49],
    [2, 4.4, 49],
    [3, 4.9, 46],
    [4, 4.3, 33],
]

stud_df = pd.DataFrame(data, columns=['Grade', 'Test_Mark', 'Time'])
stud_df

Grade  Test_Mark  Time
0      1        4.7    60
1      3        4.5    45
2      4        4.8    40
3      1        4.9    58
4      2        4.1    50
5      2        4.2    49
6      2        4.4    49
7      3        4.9    46
8      4        4.3    33

In [119]:
gr_stud_df = stud_df.groupby(by='Grade')

# Тип результата - pd.DataFrameGroupBy
print(type(gr_stud_df))

# Таким образом увидим словарь:
#   Ключи - названия групп
#   Значения - индексы из данных для группы
gr_stud_df.groups

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


{1: Int64Index([0, 3], dtype='int64'),
 2: Int64Index([4, 5, 6], dtype='int64'),
 3: Int64Index([1, 7], dtype='int64'),
 4: Int64Index([2, 8], dtype='int64')}

In [120]:
gr_stud_df.agg('mean')

Test_Mark       Time
Grade                      
1       4.800000  59.000000
2       4.233333  49.333333
3       4.700000  45.500000
4       4.550000  36.500000

In [121]:
# Более сложный вариант - найдем средние и минимальные время и оценку 

gr_stud_df.agg(['mean', 'min'])

Test_Mark            Time    
           mean  min       mean min
Grade                              
1      4.800000  4.7  59.000000  58
2      4.233333  4.1  49.333333  49
3      4.700000  4.5  45.500000  45
4      4.550000  4.3  36.500000  33

In [122]:
# Или зададим правила для каждого признака по отдельности

res = gr_stud_df.agg({
    'Test_Mark': ['mean', 'min'],
    'Time': ['min']
})

print(type(res))
res

<class 'pandas.core.frame.DataFrame'>


Test_Mark      Time
           mean  min  min
Grade                    
1      4.800000  4.7   58
2      4.233333  4.1   49
3      4.700000  4.5   45
4      4.550000  4.3   33

In [123]:
# Для обращения к данным просто используем несколько индексов, 
#   так как это DataFrame
res['Test_Mark']['mean']

Grade
1    4.800000
2    4.233333
3    4.700000
4    4.550000
Name: mean, dtype: float64

In [126]:
df = pd.DataFrame({
    'x1': np.random.randint(10, 100, size=(200, )),
    'x2': np.random.choice(['low', 'high', 'medium'], size=(200, )),
    'x3': np.random.randint(-20, 30, size=(200, )),
})
df.head()
data_gr = df.groupby(by='x2')
data_gr.agg(['mean', 'max'])

x1            x3    
             mean max      mean max
x2                                 
high    58.554054  98  3.837838  29
low     58.278689  98  5.213115  29
medium  49.507692  97  1.861538  28

In [127]:
import string

df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df.head(3)

x1  x2  x3
A   2   9   0
B   8   7   8
C   1   3   8

In [128]:
# Для сохранения задается путь до файла
df.to_csv('my_first_file.csv')

In [129]:
df = pd.read_csv('my_first_file.csv')
df.head(3)

Unnamed: 0  x1  x2  x3
0          A   2   9   0
1          B   8   7   8
2          C   1   3   8

In [130]:
df = pd.read_csv('my_first_file.csv', index_col=0)
df.head(3)

x1  x2  x3
A   2   9   0
B   8   7   8
C   1   3   8

ЗАДАНИЕ 8: Разберитесь в аргументах DataFrame.to_csv() и сохраните данные в файл так, чтобы в файл индекс не сохранялся.

In [136]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df.to_csv('my_second_file.csv', index = False)
df.head(3)

x1  x2  x3
A   8   2   8
B   9   4   4
C   8   3   3

ЗАДАНИЕ 9: Создайте фрейм с тремя колонками:

Колонка с именами (тип - объекты);
Колонка с стажем работы (тип - вещественный);
Колонка с возрастом (тип - целочисленный);
Колонка с названием любимого цвета (тип - категориальный);
Имена колонок и значения любые, не менее трех записей (строк) в фрейме.

In [141]:
df = pd.DataFrame({
    'Name': ['Polya', 'Boris', 'Harvey', 'Mike'],
    'Experience': [0.3, 0.5, 20, 3],
    'Age': [21, 23, 41, 26],
    'FavColour': pd.Categorical(['Blue', 'Fade', 'Black', 'Black'])
})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   Name        4 non-null      object  
 1   Experience  4 non-null      float64 
 2   Age         4 non-null      int64   
 3   FavColour   4 non-null      category
dtypes: category(1), float64(1), int64(1), object(1)
memory usage: 332.0+ bytes


Выберите числа в ряду ds1, которых нет в ряду ds2:

Почитайте и примение метод Series.isin()

In [143]:
ds1 = pd.Series([1, 2, 3, 4, 5])
ds2 = pd.Series([4, 5, 6, 7, 8, 1, 9])
isin = ds1.isin(ds2)
list(ds1[~isin])

[2, 3]

Оставьте в ряду два наиболее частых значения, остальные замените значением 'Другое':

Подсказка 1
Для определения наиболее частых значений воспользуйтесь методом Series.value_counts()

Подсказка 2
Чтобы получить наиболее частые значения можно воспользоваться результатом Series.value_counts() - атрибутом Series.index

Подсказка 3
Получив наиболее частые значения, можно индексировать другие через маску метода Series.isin()

In [147]:
ds = pd.Series([2, 2, 2, 4, 4, 4, 3, 1, 1, 1, 1, 4])
values = ds.value_counts().index[0:2]
isin = ds.isin(values)
ds[~isin]='Other'
list(ds)

['Other', 'Other', 'Other', 4, 4, 4, 'Other', 1, 1, 1, 1, 4]

Сделайте каждую первую букву в словах ряда заглавной:

In [149]:
ds = pd.Series(['how', 'to', 'use', 'pandas?'])
def FirstLetter(let):
  let = let[0].upper() + let[1:]
  return let

list(ds.apply(FirstLetter))

['How', 'To', 'Use', 'Pandas?']

Выберите записи с максимальным значением по колонке x1:

In [156]:
df = pd.DataFrame(
    np.random.randint(0, 4, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
mask = df['x1'].max()
df[df['x1']==mask]

x1  x2  x3
2    3   3   3
7    3   2   3
11   3   0   0
12   3   3   3
14   3   3   2

Выведите количество пропусков в каждой колонке данных:

In [162]:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')
df
print(df.isna().aggregate('sum', axis='rows'))

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64


Замените пропущенные значения в колонке Min.Price средним значениям по этой колонке:

In [170]:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
print(df)
df['Min.Price'].isna().sum()
#print(df.isna().aggregate('sum', axis='rows'))

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9       18.8      25.0   
1           NaN   Legend  Midsize  29.200000   33.9       38.7      18.0   
2          Audi       90  Compact  25.900000   29.1       32.3      20.0   
3          Audi      100  Midsize  17.118605   37.7       44.6      19.0   
4           BMW     535i  Midsize  17.118605   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3       23.7      18.0   
91        Volvo      240  Compact  21.800000   22.7       23.5      21.0   
92          NaN      850  Midsize  24.800000   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

0

Отсортируйте и выведите фрейм с колонками в алфавитном порядке:

In [176]:
df = pd.DataFrame(np.random.randint(0, 10, size=(5, 6)), columns=list('fbecda'))
df[list(df.columns.sort_values(ascending=False))]

f  e  d  c  b  a
0  5  5  6  1  3  6
1  4  1  3  6  9  2
2  1  2  3  4  3  4
3  9  5  5  9  6  3
4  2  8  4  4  0  3

Отобразите каждую 20ю запись во фрейме и только колонки Manufacturer, Model, Type:

In [177]:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')
df.iloc[20::20, :].loc[:, ['Manufacturer', 'Model', 'Type']]

Manufacturer    Model     Type
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

Получите ряд, который содержит длины строк:

In [182]:
ds = pd.Series(['how', 'to', 'use', 'pandas?'])
ds.apply(lambda x: len(x))

0    3
1    2
2    3
3    7
dtype: int64