MASSIVE SECTION:

In [2]:
import numpy as np
# Самый просто способ создать массив numpy - взять уже существующий list и передать в функцию np.array()
arr_1d = np.array([1, 2, 3])

In [3]:
# Теперь проверим 
#   - тип объекта c помощью функции type()
#   - размерность с помощью аттрибута .shape
#   - доступ по индексам, как у обычного list

# Для отладки можно выводить небольшие массивы прямо через print()

print(arr_1d)
print(type(arr_1d))
print(arr_1d.shape)
print(arr_1d[0])
print(arr_1d[2])
print(arr_1d[-1])

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1
3
3


In [4]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
print(arr_2d)
print(type(arr_2d))
print(arr_2d.shape)
print(arr_2d[0, 0])
print(arr_2d[1, 2])
print(arr_2d[1, 0])

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
1
6
4


In [6]:
# Создание массива фиксированного размера
np.ndarray((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.full((3, 4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [10]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

np.zeros_like(arr_2d)

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
# Создание массива со случайными значениями в интервале [0; 1.0)
np.random.random((2,2))

array([[0.46204315, 0.34210909],
       [0.85977557, 0.80796348]])

In [13]:
np.arange(start=1, stop=10, step=1.5)

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

In [14]:
# Также создание диапазона значений, но уже с заданием количества элементов
# (*) stop уже входит в создаваемый диапазон
np.linspace(start=1, stop=2, num=10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

INDEX SECTION:

In [15]:
# Для начала на простом списке (1D массива)
# Следующее создание массива можно заменить list(range(1, 11))
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
# Простая индексация
print(arr[0])
print(arr[-2])
print(arr[5])

1
9
6


In [17]:
# Получение части массива от 2го элемента до 6го (не включительно) 
#   с шагом 2 
print(arr[2:8:2])

[3, 5, 7]


In [19]:
#Если шаг не задан, то он равен единице (при этом второй раз : не пишется)
print(arr[2:8])

[3, 4, 5, 6, 7, 8]


In [20]:
# Шаг может быть и отрицательным (индексы меняются местами)
print(arr[8:2:-1])

[9, 8, 7, 6, 5, 4]


In [21]:
# Если не задавать index_start или index_end, 
#   то они будут равны индексу начала и конца массива
print(arr[2:])
print(arr[:8])

[3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8]


In [22]:
# Можно комбинировать один из индексов и шаг
print(arr[2::2])
print(arr[:8:3])

[3, 5, 7, 9]
[1, 4, 7]


In [23]:
# И не забываем, что все трюки работают и на запись
new_arr = list(range(1, 11))

new_arr[1:5] = arr[:4]
print(new_arr)

[1, 1, 2, 3, 4, 6, 7, 8, 9, 10]


In [24]:
# Не самая полезная, но все же запись (получить весь диапазон)
print(arr[:])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


ЗАДАНИЕ 1: Объясните результат операции:

In [35]:
print(arr[:5:-2])

[10, 8]


Выводим массив начиная с конца, т.к. исполузется шаг -2, до 5 элемента массива (5 не включается) т.е. 9 и 7 элементы.

ЗАДАНИЕ 2: Получите массив без первого и двух последних элементов:

In [40]:
data = list(range(10))
print(data)
print(data[::-1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


ЗАДАНИЕ 3: Получите массив без первого и двух последних элементов:

In [45]:
data = list(range(10))
print(data)
print(data[1:8])
# TODO - [1, 2, 3, 4, 5, 6, 7]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7]


INDEXATION IN MATRIX SECTION:

In [5]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
# Получим вторую строку массива
print(arr[2])
print(arr[2, :])

[ 9 10 11 12]
[ 9 10 11 12]


-Третью, если быть точнее, хотя если считать с нуля, то конечно вторую. Но это больше по python-новски, нежели по-русски. Хотя, в целом, курс и предполагает...-

In [11]:
# Получим первую колонку массива
print(arr[:, 1])
print(arr[:, 0])

[ 2  6 10]
[1 5 9]


In [10]:
# Получить первые два элемента (первые две колонки) первого ряда
print(arr[1, :2])

[5 6]


-А вот это вызывает у меня смятение. Возможно, правда, я чего - то не понял.-

-UPD: Понял, не учел, что "первый" это "второй", и последовательность до второго означает, что записываем нулевой и первый, а второй не включаем. Phew :)-

In [14]:
# Можно повторять целые части массива
#   (но при этом должны соотноситься размерности)
# ndarray.copy() - функция копирования массива
# Копируем, чтобы не изменить оригинальный
new_arr = arr.copy()
print(arr)

new_arr[2, :] = arr[1, :]
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [15]:
# При этом, такая индексация - это новый массив со своей размерностью.
print(arr[:2, :2])
print(arr[:2, :2].shape)

[[1 2]
 [5 6]]
(2, 2)


In [16]:
# В качестве индексов можно также задавать другие массивы
# Получаем первую и последнюю колонки
print(arr[:, [0, -1]])

[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [17]:
# И таким образом никто не заставляет писать в том же порядке индексы
# Перемешаем ряды
print(arr[[2, 0, 1], :])

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [18]:
# Также, можно комбинировать способы задания
print(arr[[2, 0], [1, 3]])
# То же самое, только первая запись дает массив
print(arr[2, 1], arr[0, 3])

[10  4]
10 4


In [20]:
# Создаем список возможных индексов для рядов массива
row_indices = list(range(arr.shape[0]))
print(row_indices)

# Переворачиваем его
row_indices = list(reversed(row_indices))
print(row_indices)

# Используем для индексации
print('----------------')
print(arr[row_indices])

[0, 1, 2]
[2, 1, 0]
----------------
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


ЗАДАНИЕ 4: Получите массив без крайних рядов и колонок (по одной с каждой стороны)

In [33]:
data = np.random.randint(low=0, high=10, size=(5, 6))
print(data)
print('----------------')
print(data[1:-1,1:-1])
print('----------------')


[[1 0 8 4 9 5]
 [0 1 4 0 3 4]
 [9 9 1 8 2 4]
 [1 3 3 4 6 0]
 [8 7 5 7 4 2]]
----------------
[[1 4 0 3]
 [9 1 8 2]
 [3 3 4 6]]
----------------


ЗАДАНИЕ 5: Произведите перемешивание колонок с помощью функции numpy.random.permutation():

In [49]:
data = np.random.randint(low=0, high=10, size=(3, 6))
print(data)
print('----------------')
col_ind = list(range(data.shape[1]))
print(col_ind)
print('----------------')
new_col_ind = np.random.permutation(col_ind)
print(new_col_ind)
print('----------------')
print(data[:, new_col_ind])
print('----------------')

[[7 8 3 4 7 4]
 [1 1 6 6 0 9]
 [1 3 1 8 9 2]]
----------------
[0, 1, 2, 3, 4, 5]
----------------
[4 2 0 1 3 5]
----------------
[[7 3 7 8 4 4]
 [0 6 1 1 6 9]
 [9 1 1 3 8 2]]
----------------


TYPES OF DATA IN MASSIVES SECTION:

In [50]:
# Создадим массив без задания типа - тип будет определен автоматически
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.dtype)

# int, так как все элементы являются целочисленными

int32


In [51]:
# Изменим один элемент на вещественный
arr = np.array([[1.5, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.dtype)

# Один из элементов float, поэтому весь массив будет float

float64


In [52]:
# Зададим явно тип массива
# Хоть массив и содержит вещественные числа
# мы создаем массив целочисленных, что приводит
# к округлению
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]], dtype=int)
print(arr)
print(arr.dtype)

[[ 1  1  2]
 [-1  2 -1]]
int32


In [53]:
# Создаем массив вещественных
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]])
print(arr)
print(arr.dtype)
print('----------')
# Но в какой-то момент нам нужно привести массив к целочисленным
# Воспользуемся методом ndarray.astype()
arr = arr.astype(int)
print(arr)
print(arr.dtype)

[[ 1.1  1.6  2.4]
 [-1.7  2.6 -1.2]]
float64
----------
[[ 1  1  2]
 [-1  2 -1]]
int32


In [54]:
# При этом попытки записать в целочисленный массив 
# вещественное число приводят к округлению
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]], dtype=int)
print(arr)

arr[0, 1] = 10.12
print(arr)

[[ 1  1  2]
 [-1  2 -1]]
[[ 1 10  2]
 [-1  2 -1]]



BOOLEAN OPERATIONS SECTION:


In [55]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [56]:
# Произведем сравнение с числом
result = arr > 6
print(result)
print(result.dtype)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
bool


In [57]:
result_1 = arr > 6
result_2 = arr < 10
print(result_1)
print(result_2)

print('----------')
# Следующие две операции идентичны, но для второй скобки обязательны!
print(result_1 & result_2)
print((arr > 6) & (arr < 10))

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True False False False]]
----------
[[False False False False]
 [False False  True  True]
 [ True False False False]]
[[False False False False]
 [False False  True  True]
 [ True False False False]]


In [91]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)
print()
print((arr > 5) & (arr < 8))
print()
answer = np.any((arr > 5) & (arr < 8))
print(answer)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[False False False False]
 [False  True  True False]
 [False False False False]]

True



MORE INDEXATION SECTION:


In [92]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [93]:
# Получим маску и воспользуемся ею для индексации
mask = arr > 6
print(mask)
print(arr[mask])

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 7  8  9 10 11 12]


In [94]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.flatten())

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]



MASSIVE OPERATIONS SECTION:


In [95]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [96]:
# Сложение
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [97]:
# Вычитание
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [98]:
# Поэлементное умножение
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [99]:
# Поэлементное деление
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [100]:
# Вычисление корня каждого элемента
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [101]:
# Умножение матрицы на скаляр - релизуется как поэлементное перемножение 
k = 1.5

print(k*x)

[[1.5 3. ]
 [4.5 6. ]]


In [102]:
v = np.array([1, 2])

In [103]:
# Матричное умножение реализуется через оператор @ или функцию np.dot() 
#   или метод ndarray.dot()
# Для умножения матрица-вектор

print(x @ v)
print(x.dot(v))
print(np.dot(x, v))

[ 5. 11.]
[ 5. 11.]
[ 5. 11.]


In [104]:
# Двух векторов
w = np.array([3, 4])

print(w @ v)
print(w.dot(v))
print(np.dot(w, v))

11
11
11


In [105]:
# Так и для перемножения матриц
print(x @ y)
print(x.dot(y))
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [106]:
# Для транспонирования можно воспользоваться атрибутом ndarray.T
#   или функцией np.transpose()
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)
print('--------')
print(np.transpose(x))
print(x.T)
print(x.T.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
--------
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
(3, 2)



AXIS OPERATIONS SECTION:


In [108]:
x = np.array([[1, 2, 3], [5, 4, 3]])
print(x)

[[1 2 3]
 [5 4 3]]


In [109]:
# Возьмем среднее значение всего массива
print(np.mean(x))
print(np.mean(x, axis=None))

3.0
3.0


In [110]:
# Получим сумму значений всего массива
print(np.sum(x))
print(np.sum(x, axis=None))

18
18


In [111]:
# Получим среднее по каждому столбцу
print(np.mean(x, axis=0))

# Получим среднее по каждой строке
print(np.mean(x, axis=1))

[3. 3. 3.]
[2. 4.]


ЗАДАНИЕ 6: Напишите операцию получения суммы элементов по всем стобцам:

In [134]:
data = np.random.randint(low=0, high=5, size=(3, 6))
print(data)
print()
print(np.sum(data, axis=0))

[[0 0 2 3 2 4]
 [3 4 4 2 0 2]
 [3 2 4 0 2 3]]

[ 6  6 10  5  4  9]


BROADCASTING SECTION:

In [135]:
vec = np.arange(4)
mtrx = np.ones((3, 4))
print(vec)
print(mtrx)

[0 1 2 3]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [136]:
result = np.empty_like(mtrx)

for i_row in range(mtrx.shape[0]):
    result[i_row,:] = mtrx[i_row,:] * vec

print(result)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [137]:
# Функция np.tile() повторяет массив то количество раз и по тем осям,
#   которые заданы в аргументе reps
vec_m = np.tile(vec, reps=(3, 1))
print(vec_m)
print(vec_m * mtrx)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [138]:
# Умножение, используя броадкастинг
print(vec * mtrx)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [139]:
print(2 * mtrx)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [140]:
x = np.ones((4, 1, 1))
y = np.random.randint(0, 5, size=(4, 3, 2))

print((x*y).shape)

(4, 3, 2)


In [141]:
x = np.ones((3, 1))
y = np.random.randint(0, 5, size=(4, 3, 2))

print((x*y).shape)

(4, 3, 2)


In [142]:
x = np.ones((1, 3, 2))
y = np.random.randint(0, 5, size=(5, 1, 2))

print((x*y).shape)

(5, 3, 2)


RESHAPE SECTION:

In [143]:
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [144]:
mtrx = np.ndarray((4, 5), dtype=np.int32)
mtrx[0, :] = arr[:5]
mtrx[1, :] = arr[5:10]
mtrx[2, :] = arr[10:15]
mtrx[3, :] = arr[15:]

print(mtrx)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [145]:
print(arr.reshape((4, 5)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [146]:
print(arr.reshape((2, 10)))
print(arr.reshape((5, 4)))
print(arr.reshape((20, 1)))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [147]:
print(arr.reshape((4, -1)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


UNITED SECTION:

In [148]:
x = np.arange(10).reshape((2, 5))
y = np.arange(15).reshape((3, 5))

print(x)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [149]:
print(np.concatenate((x, y), axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [150]:
x = np.arange(9).reshape((3, 3))
y = np.arange(12).reshape((3, 4))
z = np.arange(15).reshape((3, 5))

print(x)
print(y)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


ЗАДАНИЕ 7: Объедините три массива вдоль колонок:

In [151]:
print(np.concatenate((x, y, z), axis=1))

[[ 0  1  2  0  1  2  3  0  1  2  3  4]
 [ 3  4  5  4  5  6  7  5  6  7  8  9]
 [ 6  7  8  8  9 10 11 10 11 12 13 14]]


ЗАДАНИЕ 8: Напишите реализацию добавления стобца единиц к матрице слева:

In [157]:
x = np.arange(1, 10).reshape((3, 3))
y = np.ones((3,1), dtype=int)
print(x)
print()
print(np.concatenate((y, x), axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 1 2 3]
 [1 4 5 6]
 [1 7 8 9]]


SORTING SECTION:

In [158]:
unsorted_arr = np.array([2, 4, 5, 1, 2, 7, 5, 0, -1, 3, 5])
sorted_arr = np.sort(unsorted_arr)

print(unsorted_arr)
print(sorted_arr)

[ 2  4  5  1  2  7  5  0 -1  3  5]
[-1  0  1  2  2  3  4  5  5  5  7]


In [159]:
sorted_indices = np.argsort(unsorted_arr)
print(sorted_indices)

# А теперь воспользуемся индексами и отобразим исходный массив с индексацией
print(unsorted_arr[sorted_indices])

[ 8  7  3  0  4  9  1  2  6 10  5]
[-1  0  1  2  2  3  4  5  5  5  7]


ЗАДАНИЕ 9: По такому же принципу именования найдите функцию, которая возвращает индекс максимального/минимального (в завимости от варианта) элемента в массиве.

Воспользуйтесь найденной функцией и найдите индексы максимальных элементов в каждом столбце 2D матрицы:

In [11]:
arr = np.array([
    [11, -1, 1, 3, 5],
    [6, 1, 0, -1, 10],
    [1, 3, 2, 3, 6],
    [5, 2, 7, 8, 9],
])
print(arr)

print(np.argmax(arr, axis=0))
print()
print(np.argmin(arr, axis=0))

[[11 -1  1  3  5]
 [ 6  1  0 -1 10]
 [ 1  3  2  3  6]
 [ 5  2  7  8  9]]
[0 2 3 3 1]

[2 0 1 1 0]


ЗАДАНИЕ 10: Напишите код сортировки массива по столбцам:

In [8]:
arr = np.array([
    [11, 2, 1, 3, 5],
    [6, 2, 0, -1, 10],
    [1, 3, 2, 3, 5],
    [5, 2, 7, 8, 9],
    ])
np.sort(arr, axis=0)

array([[ 1,  2,  0, -1,  5],
       [ 5,  2,  1,  3,  5],
       [ 6,  2,  2,  3,  9],
       [11,  3,  7,  8, 10]])

ЗАДАНИЕ 11: Создайте массив, состоящий из случайных элементов в диапазоне  [−10;20]  размером  (5,7) :

In [17]:
y = np.random.randint(-10, 20, size=(5, 7))
print(y)
print()

[[10  2 17 18 15 -6  2]
 [ 7 19 12  8 -8  3 14]
 [19 11 13  3  6 -3 19]
 [ 8  3  0 19  2 -9  9]
 [ 1 10 17 -1 16 -4  1]]



Добавьте границу в виде нулей со всех сторон 2D массива:

In [40]:
data = np.arange(1, 16).reshape((3, 5))
print(data)
x = np.zeros((1,5))
z = np.zeros((5,1))
data_m1 = np.concatenate((x, data, x), axis=0)
data_m2 = np.concatenate((z, data_m1, z), axis=1)
dtype=np.int32
data_m = np.array(data_m2, dtype=np.int32)
print(data_m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  0]
 [ 0  6  7  8  9 10  0]
 [ 0 11 12 13 14 15  0]
 [ 0  0  0  0  0  0  0]]


Разберитесь с функцией np.clip() и произведите ограничение массива, чтобы в нем значения были не более шести и не менее двух:

In [43]:
data = np.arange(1, 16).reshape((3, 5))
print(data)
np.clip(data, 2, 6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


array([[2, 2, 3, 4, 5],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

Произведите модификацию массива так, чтобы значение в колонке результата соответствовало исходному значению, возведенному в степень индекса колонки:

In [52]:
data = np.full((3, 5), fill_value=2, dtype=np.int32)
print(data)
print()
print(np.power(data, range(data.shape[1])))

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]

[[ 1  2  4  8 16]
 [ 1  2  4  8 16]
 [ 1  2  4  8 16]]


Умножьте каждую колонку на ее индекс:

In [57]:
data = np.full((3, 5), fill_value=2, dtype=np.int32)
print(data)
print()
print(np.multiply(data, range(data.shape[1])))

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]

[[0 2 4 6 8]
 [0 2 4 6 8]
 [0 2 4 6 8]]


Умножьте каждую колонку на ее индекс:

In [90]:
data = np.repeat(np.arange(1, 8), 4).reshape(7, 4)
vec = np.array([1, 2, 1, 2])
data_new = np.empty_like(data)
print(data)
print()
for i in list(range(data.shape[0])):
    if i %2 == 0:
        data_new[i, :] = np.multiply(data[i, :] , vec)
    else:
        data_new[i, :] = data[i, :]
print(data_new)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]

[[ 1  2  1  2]
 [ 2  2  2  2]
 [ 3  6  3  6]
 [ 4  4  4  4]
 [ 5 10  5 10]
 [ 6  6  6  6]
 [ 7 14  7 14]]


Определите индексы двух наибольших элементов в матрице по каждому ряду:

In [104]:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
print()
data_new = np.argsort(data, axis = 1)
print(data_new)
print()
print(data_new[:,[-1, -2]])

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [ 4 24 24 28  3 40]]

[[2 5 3 0 1 4]
 [3 0 5 4 2 1]
 [4 0 2 5 1 3]
 [4 0 1 2 3 5]]

[[4 1]
 [1 2]
 [3 1]
 [5 3]]


Выберите две случайные колонки из массива:

In [115]:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
rnd = np.random.choice(data.shape[1], 2)
print(data[:, [rnd[0], rnd[1]]])

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [ 4 24 24 28  3 40]]
[[ 8 22]
 [15 25]
 [ 9 16]
 [40 24]]


Создайте массив размером  (10,3) , который состоит из повторяющихся рядов исходного массива:

In [147]:
data = np.arange(9).reshape(3, 3)
print(data)
print()
rnd = np.random.choice(data.shape[0], 10)
print(rnd)
print()
for i in list(range(10)):
    new_data[i,:] = data[[rnd[i]], :]
print(new_data)
new_data.shape

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[1 0 1 2 0 0 1 2 1 0]

[[3 4 5]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [3 4 5]
 [0 1 2]]


(10, 3)

Соберите массив, состоящий из элементов 2й и 4й колонок и строк с 1й по 3ю:

In [151]:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 14, 9,  33, 21,  7,  6],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
print()
print(data[1:4, (2,4)])

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [14  9 33 21  7  6]
 [ 4 24 24 28  3 40]]

[[23 22]
 [ 9  0]
 [33  7]]


Инвертируйте порядок элементов в последних двух колонках:

In [155]:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 14, 9,  33, 21,  7,  6],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
print()
data[:,(-2, -1)] = data[::-1, (-2, -1)]
print(data)

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [14  9 33 21  7  6]
 [ 4 24 24 28  3 40]]

[[20 22  2 14  3 40]
 [ 7 25 23  3  7  6]
 [ 8 16  9 22  0  9]
 [14  9 33 21 22 15]
 [ 4 24 24 28 25  8]]
